name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential man-db

      - name: Build
        run: make

      - name: Run basic tests
        run: |
          echo "Hello world" > test1.txt
          echo "Another line" > test2.txt

          # Concatenate files
          ./redmond-cat test1.txt test2.txt > out.txt
          echo "== Output =="
          cat out.txt

          # Number lines
          ./redmond-cat -n test1.txt > out2.txt
          cat out2.txt

          # Squeeze blank lines
          printf "a\n\n\nb\n" | ./redmond-cat -s > out3.txt
          cat out3.txt

      - name: Check version/help
        run: |
          ./redmond-cat --version
          ./redmond-cat --help
